/*
 * Class auto generated by TexturePacker
 *
 * Contains references to each sprite within the sprite sheet.
 *
 * https://www.codeandweb.com/texturepacker
 * {{smartUpdateKey}}
 *
 */{% load TransformName %}

internal struct {{texture.trimmedName|className}}Sprites {
	{% for sprite in allSprites %}		
	internal static let {{sprite.trimmedName|swiftifyPath}}: SpriteId = {{forloop.counter0}} // {{sprite.trimmedName}}
	{% endfor %}
}